# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_index=True, default=1),
            preserve_default=False,
        ),
    ]
